nohup /usr/local/bin/php -f icon.php data/outputfile_da > logs/da.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_db > logs/db.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dc > logs/dc.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dd > logs/dd.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_de > logs/de.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_df > logs/df.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dg > logs/dg.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dh > logs/dh.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_di > logs/di.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dj > logs/dj.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dk > logs/dk.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dl > logs/dl.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dm > logs/dm.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dn > logs/dn.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_do > logs/do.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dp > logs/dp.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dq > logs/dq.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dr > logs/dr.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_ds > logs/ds.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dt > logs/dt.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_du > logs/du.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dv > logs/dv.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dw > logs/dw.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dx > logs/dx.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dy > logs/dy.log 2>&1 &
nohup /usr/local/bin/php -f icon.php data/outputfile_dz > logs/dz.log 2>&1 &